weather:
    latitude: 31.3562
    longitude: -113.526
areas:
  - Las Conchas
cache_population_searches:
    - address:
        country: 'MX'

units:
  - unit_id: 1911-89481
    unit_name: El Pelicano
  - unit_id: 1911-89483
    unit_name: La Sala
  - unit_id: 1911-89482
    unit_name: La Paloma
  - unit_id: 1911-89477
    unit_name: La Chuparosa
  - unit_id: 1911-89479
    unit_name: Courtyard 1
  - unit_id: 1911-89480
    unit_name: Courtyard 2
  - unit_id: 1911-112148
    unit_name: La Aguila
  - unit_id: 1911-124068
    unit_name: Courtyard Rooms
  - unit_id: 1911-124080
    unit_name: Upper View Rooms 1
  - unit_id: 1911-124086
    unit_name: Upper View Rooms 2
  - unit_id: 1911-124088
    unit_name: East Building
  - unit_id: 1911-124090
    unit_name: Main House
