weather:
    latitude: 31.3562
    longitude: -113.526
areas:
    - Corona del Sol
    - Costa Diamente
    - Las Conchas
    - Las Palmas
    - Mirador
    - Playa Encanto
    - Sandy Beach
cache_population_searches:
    - address:
        country: 'MX'

unit_ids:
  - 1911-112148
  - 1911-89479
  - 1911-89480
  - 1911-89477
  - 1911-89482
  - 1911-89483
  - 1911-89481
  - 1911-89478

